name: 🐛 Bug Report
description: Report a bug or issue with Hive Studio Installer
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        Please provide as much detail as possible to help us reproduce and fix the issue quickly.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've completed these steps before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the [troubleshooting guide](../docs/TROUBLESHOOTING.md)
          required: true
        - label: I am using a supported version of macOS
          required: true
        - label: I have administrator/sudo access on my system
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened vs what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run the installer with: curl -sSL https://raw.githubusercontent.com/auitenbroek1/hive-studio-installer/main/install.sh | bash
        2. During installation...
        3. Error occurs when...
        4. Expected behavior was...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear description of what actually happened
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severely does this bug impact your workflow?
      options:
        - Critical - Prevents installation completely
        - High - Installation fails with workarounds available
        - Medium - Installation succeeds but with issues
        - Low - Minor inconvenience or cosmetic issue
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: |
        Please provide your system information. You can get this by running:
        ```bash
        system_profiler SPSoftwareDataType | grep "System Version"
        uname -a
        ```
      placeholder: |
        macOS Version: 
        Processor: 
        Architecture: 
        Shell: 
    validations:
      required: true

  - type: textarea
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you run the installer?
      options:
        - One-line curl command
        - Downloaded script manually
        - Custom installation with flags
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: |
        Please include any error messages or log output.
        If the installer created log files, please include relevant portions.
      placeholder: |
        Paste error messages, log output, or stack traces here.
        You can find logs in: ~/hive-studio-installer/logs/
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Were you behind a corporate firewall?
        - Did you have any security software running?
        - Any other relevant environmental factors?

  - type: checkboxes
    id: security-check
    attributes:
      label: Security Consideration
      description: Does this bug involve security concerns?
      options:
        - label: This bug may have security implications
        - label: I have reviewed the [Security Policy](../SECURITY.md) before reporting

  - type: markdown
    attributes:
      value: |
        ---
        **Note**: For security-related issues, please follow our [Security Policy](../SECURITY.md) and report to security@hivestudio.dev instead of creating a public issue.